// Terminal.mm — shell panel on a pty. Objective-C++.
//
// How it fits together:
//   * zsh runs as `zsh -l -i +Z` (login, interactive, line editor off) on a
//     pseudo-terminal from forkpty(). The kernel's line discipline handles
//     Ctrl+C -> SIGINT, echo, and the window size, like any terminal.
//   * ZDOTDIR points at a tiny generated .zshenv that restores the user's own
//     ZDOTDIR, loads their startup files as usual, and installs precmd/preexec
//     hooks just before the first prompt. The hooks emit OSC 133 marks (prompt,
//     command start, command end + status) and OSC 7 (cwd), and blank the
//     prompt text, since the panel draws its own.
//   * TerminalStream (pure C++) turns the pty bytes into styled lines and
//     those events. The last line of the output view is "live": the stream
//     re-sends it whole whenever it changes (colors, \r progress lines,
//     erase-in-line), and the view replaces it until a newline ends it.
//   * Typed lines go to the pty. At the prompt they are commands; while a
//     command runs they are that program's input. Echo is off while zsh reads
//     a command (the panel shows it in the header instead) and on while a
//     command runs, so a program that turns echo off (a password prompt) gets
//     a secure input field.
//   * TerminalScreen (pure C++) reads the same bytes as a cell grid, all the
//     time, so it is current whenever it is needed. The panel shows it in
//     place of the log (grid mode) while the program is on the alternate
//     screen (vim, less, htop, man), or when a running command has kept the
//     pty out of canonical mode for a moment without one (git's less -X, a
//     REPL, ssh); the latter lasts until the command ends. In grid mode keys
//     go straight to the pty. The log stream leaves alternate-screen text
//     out, so the log is intact when the grid goes away.
#import "Terminal.h"
#import "AppSettings.h"
#import "TerminalGridView.h"
#include "TerminalStream.h"
#include "TerminalScreen.h"

#include <util.h>
#include <termios.h>
#include <sys/ioctl.h>
#include <sys/wait.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <string>
#include <vector>

extern char **environ;

static NSColor *THex(unsigned int rgb) {
    return [NSColor colorWithSRGBRed:((rgb >> 16) & 0xFF) / 255.0
                               green:((rgb >> 8)  & 0xFF) / 255.0
                                blue:( rgb        & 0xFF) / 255.0
                               alpha:1.0];
}

// The generated .zshenv. zsh reads $ZDOTDIR/.zshenv first; this one hands
// ZDOTDIR back to the user straight away, so their .zprofile/.zshrc/.zlogin
// load normally and child shells never see ours.
static const char *kZshIntegration = R"ZSH(# Generated by MiniCode for its terminal panel. Safe to delete.
if [[ -n "${MINICODE_USER_ZDOTDIR+x}" ]]; then
  ZDOTDIR=$MINICODE_USER_ZDOTDIR
else
  unset ZDOTDIR
fi
unset MINICODE_USER_ZDOTDIR
[[ -f "${ZDOTDIR:-$HOME}/.zshenv" ]] && builtin source "${ZDOTDIR:-$HOME}/.zshenv"

if [[ -o interactive ]]; then
  # No "%" end-of-line marker; these print before precmd, so set them now.
  unsetopt PROMPT_SP PROMPT_CR

  __minicode_precmd() {
    local rc=$?
    builtin print -rn -- $'\e]133;D;'"$rc"$'\a\e]7;file://'"$HOST${PWD//\%/%25}"$'\a'
    /bin/stty icanon isig -echo 2>/dev/null
    PS1='' PS2='' RPS1='' RPS2=''
    builtin print -rn -- $'\e]133;A\a'
  }
  __minicode_preexec() {
    /bin/stty echo 2>/dev/null
    builtin print -rn -- $'\e]133;C\a'
  }
  # Runs at the first prompt, after the user's startup files, so our hook is
  # last in line and has the final say over the prompt.
  __minicode_install() {
    precmd_functions=(${precmd_functions:#__minicode_install} __minicode_precmd)
    preexec_functions+=(__minicode_preexec)
    setopt HIST_IGNORE_SPACE
    unsetopt PROMPT_SP PROMPT_CR
    __minicode_precmd
  }
  precmd_functions+=(__minicode_install)
fi
)ZSH";

// Write the integration file; returns its directory, or nil on failure.
static NSString *IntegrationDirectory(void) {
    NSString *dir = [NSTemporaryDirectory()
        stringByAppendingPathComponent:@"MiniCode-zsh"];
    NSFileManager *fm = [NSFileManager defaultManager];
    if (![fm createDirectoryAtPath:dir withIntermediateDirectories:YES
                        attributes:@{NSFilePosixPermissions: @0700} error:nil])
        return nil;
    NSString *file = [dir stringByAppendingPathComponent:@".zshenv"];
    NSString *body = [NSString stringWithUTF8String:kZshIntegration];
    if (![body writeToFile:file atomically:YES encoding:NSUTF8StringEncoding
                     error:nil])
        return nil;
    return dir;
}

// Read-only output view. A plain click focuses the input line; a drag still
// selects text for copying.
@interface TerminalOutputView : NSTextView
@property(nonatomic, copy) void (^onPlainClick)(void);
@end
@implementation TerminalOutputView
- (void)mouseDown:(NSEvent *)event {
    [super mouseDown:event];   // runs selection tracking until mouseUp
    if (self.selectedRange.length == 0 && self.onPlainClick) self.onPlainClick();
}
@end

// Marks output drawn in the default foreground (value: whether it is dim), so
// a settings change can recolor it in place.
static NSString *const kDefaultFgAttribute = @"MCTerminalDefaultForeground";

@interface TerminalView () <NSTextFieldDelegate> {
    NSString *_cwd;
    NSMutableArray<NSString *> *_history;
    NSInteger _historyIdx;

    TerminalStream _stream;
    dispatch_queue_t _ioQueue;
    dispatch_source_t _readSource;
    int _master;                 // pty master fd, -1 when no shell
    pid_t _shellPid;             // 0 when no shell
    int _generation;             // bumps per shell, so stale output is ignored
    NSDate *_shellStarted;
    BOOL _integrated;            // the shell integration file was written
    struct winsize _winsize;

    BOOL _atPrompt;              // zsh is waiting for a command
    BOOL _commandStarted;        // saw 133;C for the command in flight
    BOOL _userCommand;           // the command in flight came from the input
    NSUInteger _liveStart;       // where the live line begins in the output

    TerminalScreen _screen;      // the same output as a cell grid
    BOOL _gridMode;              // the grid is showing instead of the log
    BOOL _stickyGrid;            // this command went raw: grid until it ends
    int _rawTicks;               // consecutive polls that found raw mode
    NSTimer *_rawTimer;          // polls termios while a command runs
}
@property(nonatomic, strong) TerminalGridView *grid;
@property(nonatomic, strong) NSScrollView *outScroll;
@property(nonatomic, strong) TerminalOutputView *output;
@property(nonatomic, strong) NSTextField *prompt;
@property(nonatomic, strong) NSTextField *input;
@property(nonatomic, strong) NSSecureTextField *secureInput;
@end

@implementation TerminalView

- (instancetype)initWithDirectory:(NSString *)dir {
    if ((self = [super initWithFrame:NSMakeRect(0, 0, 400, 220)])) {
        _cwd = dir.length ? dir : NSHomeDirectory();
        _history = [NSMutableArray array];
        _historyIdx = 0;
        _master = -1;
        _ioQueue = dispatch_queue_create("minicode.terminal.io",
                                         DISPATCH_QUEUE_SERIAL);
        self.wantsLayer = YES;
        [self buildViews];
        [self applySettings];
        [[NSNotificationCenter defaultCenter]
            addObserver:self selector:@selector(applySettings)
                   name:MCSettingsDidChangeNotification object:nil];
        [self appendLine:@"MiniCode terminal — zsh on a pty. Ctrl+C interrupts, "
                          "`clear` resets the panel."
                   color:THex(0x6A9955)];
        [self updatePrompt];
        [self startShell];
    }
    return self;
}

- (NSTextField *)makeInputField:(Class)cls {
    NSTextField *f = [[cls alloc] init];
    f.font = [NSFont monospacedSystemFontOfSize:12 weight:NSFontWeightRegular];
    f.bezeled = NO;
    f.focusRingType = NSFocusRingTypeNone;
    f.bordered = NO;
    f.drawsBackground = YES;
    f.delegate = self;
    f.target = self;
    f.action = @selector(inputEntered:);
    [self addSubview:f];
    return f;
}

- (void)buildViews {
    // Output (read-only, monospaced, selectable).
    self.outScroll = [[NSScrollView alloc] init];
    self.outScroll.hasVerticalScroller = YES;
    self.outScroll.drawsBackground = NO;
    self.output = [[TerminalOutputView alloc] initWithFrame:self.bounds];
    __weak TerminalView *weakSelf = self;
    self.output.onPlainClick = ^{ [weakSelf focusInput]; };
    self.output.editable = NO;
    self.output.selectable = YES;
    self.output.richText = YES;
    self.output.drawsBackground = NO;
    self.output.textContainerInset = NSMakeSize(6, 6);
    // No extra padding, so the log wraps at the same column count the pty
    // reports (updateWindowSize measures with the grid's metrics).
    self.output.textContainer.lineFragmentPadding = 0;
    self.output.verticallyResizable = YES;
    self.output.horizontallyResizable = NO;
    self.output.textContainer.widthTracksTextView = YES;
    self.output.autoresizingMask = NSViewWidthSizable;
    self.outScroll.documentView = self.output;
    [self addSubview:self.outScroll];

    // Prompt label + input field (and a secure twin for hidden input).
    self.prompt = [NSTextField labelWithString:@"❯"];
    self.prompt.font = [NSFont monospacedSystemFontOfSize:12
                                                   weight:NSFontWeightBold];
    self.prompt.textColor = THex(0x4EC9B0);
    self.prompt.backgroundColor = [NSColor clearColor];
    [self addSubview:self.prompt];

    self.input = [self makeInputField:[NSTextField class]];
    self.input.placeholderString = @"Enter a command…";
    self.secureInput = (NSSecureTextField *)
        [self makeInputField:[NSSecureTextField class]];
    self.secureInput.placeholderString = @"Hidden input (the program turned echo off)";
    self.secureInput.hidden = YES;

    // The cell grid for full-screen programs, over everything else.
    self.grid = [[TerminalGridView alloc] initWithFrame:self.bounds];
    self.grid.screen = &_screen;
    self.grid.hidden = YES;
    self.grid.onInput = ^(NSData *bytes) {
        TerminalView *s = weakSelf;
        if (s) [s sendBytes:(const char *)bytes.bytes length:bytes.length];
    };
    [self addSubview:self.grid];
}

// Colors from the settings file. Output already on screen in the default
// foreground is recolored too; explicitly colored output keeps its colors.
- (void)applySettings {
    AppSettings *cfg = [AppSettings shared];
    self.layer.backgroundColor = [cfg background:Surface::Terminal].CGColor;
    NSColor *inputBg = MCColor(cfg.settings.terminalInputBackground());
    NSColor *inputText = MCColor(cfg.settings.terminalInputText());
    for (NSTextField *f in @[self.input, self.secureInput]) {
        f.backgroundColor = inputBg;
        f.textColor = inputText;
    }
    NSTextStorage *ts = self.output.textStorage;
    NSColor *fg = [cfg text:Surface::Terminal];
    [ts beginEditing];
    [ts enumerateAttribute:kDefaultFgAttribute inRange:NSMakeRange(0, ts.length)
                   options:0 usingBlock:^(id dim, NSRange r, BOOL *stop) {
        (void)stop;
        if (!dim) return;
        NSColor *c = [dim boolValue]
            ? [fg colorWithAlphaComponent:fg.alphaComponent * 0.6] : fg;
        [ts addAttribute:NSForegroundColorAttributeName value:c range:r];
    }];
    [ts endEditing];
    [self.grid screenChanged];
}

// Manual layout — reliable regardless of how the host sizes us.
- (void)setFrameSize:(NSSize)newSize {
    [super setFrameSize:newSize];
    [self layoutChildren];
}

- (void)layoutChildren {
    CGFloat W = self.bounds.size.width, H = self.bounds.size.height;
    const CGFloat inH = 26, promptW = 20;
    self.outScroll.frame = NSMakeRect(0, inH, W, MAX(0, H - inH));
    self.prompt.frame = NSMakeRect(6, 4, promptW, 18);
    NSRect field = NSMakeRect(6 + promptW, 2, MAX(0, W - promptW - 12), 22);
    self.input.frame = field;
    self.secureInput.frame = field;
    self.grid.frame = self.bounds;
    [self updateWindowSize];
}

- (NSTextField *)activeInput {
    return self.secureInput.hidden ? self.input : self.secureInput;
}

- (void)focusInput {
    if (_gridMode) [self.window makeFirstResponder:self.grid];
    else [self.window makeFirstResponder:[self activeInput]];
}

// Is keyboard focus somewhere in this panel?
- (BOOL)hasFocus {
    id fr = self.window.firstResponder;
    return fr == self || fr == self.grid || [self isEditing:self.input] ||
           [self isEditing:self.secureInput];
}

// Show the grid while the program needs a screen, the log otherwise.
- (void)updateMode {
    BOOL want = _master >= 0 && (_screen.altScreen() || _stickyGrid);
    if (want == _gridMode) return;
    BOOL hadFocus = [self hasFocus];
    _gridMode = want;
    self.grid.hidden = !want;
    self.outScroll.hidden = want;
    self.prompt.hidden = want;
    self.input.hidden = want;
    self.secureInput.hidden = YES;
    if (!want) {
        [self updateSecureInput];
        [self scrollToEnd];
    }
    [self.grid screenChanged];
    if (hadFocus) [self focusInput];
}

// While a command runs, watch for it taking the pty out of canonical mode
// without switching to the alternate screen (git's `less -X`, a REPL, ssh).
// It must stay that way for two polls, so a program that only flips modes
// briefly (less -F on short output) never flashes the grid.
- (void)startRawWatch {
    if (_rawTimer) return;
    _rawTicks = 0;
    __weak TerminalView *weakSelf = self;
    _rawTimer = [NSTimer scheduledTimerWithTimeInterval:0.1 repeats:YES
                                                  block:^(NSTimer *t) {
        (void)t;
        [weakSelf checkRawMode];
    }];
}

- (void)stopRawWatch {
    [_rawTimer invalidate];
    _rawTimer = nil;
    _rawTicks = 0;
}

- (void)checkRawMode {
    if (_master < 0 || !_commandStarted || _atPrompt) { _rawTicks = 0; return; }
    struct termios t;
    BOOL raw = tcgetattr(_master, &t) == 0 && (t.c_lflag & ICANON) == 0;
    _rawTicks = (raw && !_screen.altScreen()) ? _rawTicks + 1 : 0;
    if (_rawTicks >= 2 && !_stickyGrid) {
        _stickyGrid = YES;
        [self updateMode];
    }
}

// Clicks on the terminal's own background (padding/gaps) also focus input.
- (void)mouseDown:(NSEvent *)event {
    [super mouseDown:event];
    [self focusInput];
}

- (void)setDirectory:(NSString *)dir {
    if (!dir.length) return;
    _cwd = dir;
    [self updatePrompt];
    if (_atPrompt) {   // move the live shell too (space: kept out of history)
        _atPrompt = NO;
        [self sendText:[NSString stringWithFormat:@" cd %@\n", [self quote:dir]]];
    }
}

- (void)updatePrompt {
    self.prompt.toolTip = _cwd;
}

// ---------------------------------------------------------------- input
- (void)inputEntered:(id)sender {
    NSTextField *field = sender;
    NSString *line = field.stringValue;
    field.stringValue = @"";

    if (_shellPid <= 0) {   // the shell exited and wasn't restarted yet
        [self startShell];
        return;
    }

    if (_integrated && !_atPrompt) {
        // Input for the running program, or the next line of a multi-line
        // command zsh is still reading. Once the command runs the pty echoes
        // what we send (unless the program disabled echo); before that, echo
        // is off, so show the line ourselves.
        if (!_commandStarted && field == self.input)
            [self appendLine:line color:THex(0x569CD6)];
        [self sendText:[line stringByAppendingString:@"\n"]];
        return;
    }

    NSString *abbrev = [_cwd stringByAbbreviatingWithTildeInPath];
    [self ensureNewline];
    [self appendLine:[NSString stringWithFormat:@"%@ ❯ %@", abbrev, line]
               color:THex(0x569CD6)];

    NSString *trimmed = [line stringByTrimmingCharactersInSet:
                         [NSCharacterSet whitespaceCharacterSet]];
    if (!trimmed.length) return;
    [_history addObject:line];
    _historyIdx = _history.count;
    if ([trimmed isEqualToString:@"clear"]) {   // handled locally
        self.output.string = @"";
        _liveStart = 0;
        _stream.breakLine();
        _screen.feed("\x1b[H\x1b[2J");
        return;
    }

    if (_integrated) {
        _atPrompt = NO;
        _commandStarted = NO;
        _userCommand = YES;
    }
    [self sendText:[line stringByAppendingString:@"\n"]];
}

// Is `field`'s field editor the current first responder?
- (BOOL)isEditing:(NSTextField *)field {
    id fr = self.window.firstResponder;
    return [fr isKindOfClass:[NSTextView class]] &&
           ((NSTextView *)fr).delegate == (id)field;
}

// Up/Down arrow -> command history. Control keys -> the pty.
- (BOOL)control:(NSControl *)control textView:(NSTextView *)tv
    doCommandBySelector:(SEL)sel {
    NSEvent *ev = NSApp.currentEvent;
    NSEventModifierFlags mods = ev.modifierFlags &
        NSEventModifierFlagDeviceIndependentFlagsMask;
    if (ev.type == NSEventTypeKeyDown &&
        (mods & NSEventModifierFlagControl) &&
        !(mods & (NSEventModifierFlagCommand | NSEventModifierFlagOption))) {
        NSString *key = ev.charactersIgnoringModifiers.lowercaseString;
        NSTextField *field = (NSTextField *)control;
        BOOL running = _integrated ? !_atPrompt : YES;
        if ([key isEqualToString:@"c"]) {
            field.stringValue = @"";
            if (running) [self sendControl:0x03];   // SIGINT via the tty
            return YES;
        }
        if ([key isEqualToString:@"d"] && field.stringValue.length == 0) {
            if (running) [self sendControl:0x04];   // EOF for the program
            return YES;                             // never exits the shell
        }
        if ([key isEqualToString:@"z"] && running) {
            [self sendControl:0x1A];                // SIGTSTP
            return YES;
        }
        if ([key isEqualToString:@"\\"] && running) {
            [self sendControl:0x1C];                // SIGQUIT
            return YES;
        }
    }

    if (control == self.secureInput) return NO;   // no history for secrets
    if (sel == @selector(moveUp:)) {
        if (_historyIdx > 0) {
            _historyIdx--;
            self.input.stringValue = _history[_historyIdx];
        }
        return YES;
    }
    if (sel == @selector(moveDown:)) {
        if (_historyIdx < (NSInteger)_history.count - 1) {
            _historyIdx++;
            self.input.stringValue = _history[_historyIdx];
        } else {
            _historyIdx = _history.count;
            self.input.stringValue = @"";
        }
        return YES;
    }
    return NO;
}

// Show the secure field while a running program has echo turned off.
- (void)updateSecureInput {
    if (_gridMode) return;       // the grid takes keys itself
    BOOL hidden = NO;
    if (_master >= 0 && _commandStarted && !_atPrompt) {
        struct termios t;
        if (tcgetattr(_master, &t) == 0) hidden = (t.c_lflag & ECHO) == 0;
    }
    if (hidden == !self.secureInput.hidden) return;
    NSTextField *from = [self activeInput];
    BOOL hadFocus = [self isEditing:from];
    self.secureInput.hidden = !hidden;
    self.input.hidden = hidden;
    NSTextField *to = [self activeInput];
    to.stringValue = @"";
    from.stringValue = @"";
    if (hadFocus) [self.window makeFirstResponder:to];
}

// ------------------------------------------------------------ the pty shell
- (void)dealloc {
    [self stopShell];
}

- (void)stopShell {
    _generation++;                     // ignore anything still in flight
    [self stopRawWatch];
    if (_readSource) {
        dispatch_source_cancel(_readSource);   // closes the fd
        _readSource = nil;
    }
    if (_shellPid > 0) kill(_shellPid, SIGHUP);
    _shellPid = 0;
    _master = -1;
}

// Rows and columns of grid cells that fit the panel, pushed to the pty so
// programs that format for the width (ls, git) and full-screen programs get
// it right; the kernel sends SIGWINCH to the foreground job on a change. The
// same size serves both modes, so switching never resizes the program.
- (void)updateWindowSize {
    NSSize cell = [TerminalGridView cellSize];
    CGFloat pad = [TerminalGridView padding];
    NSSize size = self.bounds.size;
    // A collapsed or not-yet-laid-out panel keeps the last size, rather than
    // squeezing the screen (and cutting its lines) down to nothing.
    if (size.width < 100 || size.height < 60) {
        if (_winsize.ws_col) return;
        size = NSMakeSize(MAX(size.width, 400), MAX(size.height, 220));
    }
    struct winsize ws = {};
    ws.ws_col = (unsigned short)MAX(20, floor((size.width - 2 * pad) / cell.width));
    ws.ws_row = (unsigned short)MAX(5, floor((size.height - 2 * pad) / cell.height));
    ws.ws_xpixel = (unsigned short)(ws.ws_col * cell.width);
    ws.ws_ypixel = (unsigned short)(ws.ws_row * cell.height);
    if (ws.ws_col == _winsize.ws_col && ws.ws_row == _winsize.ws_row) return;
    _winsize = ws;
    _screen.resize(ws.ws_col, ws.ws_row);
    [self.grid screenChanged];
    if (_master >= 0) ioctl(_master, TIOCSWINSZ, &_winsize);
}

- (void)startShell {
    [self stopShell];

    NSString *zdot = IntegrationDirectory();
    _integrated = zdot != nil;
    if (!_integrated)
        [self appendLine:@"Could not write the shell integration file; "
                          "commands still run, but without exit status or "
                          "directory tracking." color:THex(0xF48771)];

    // Everything the child needs is prepared before fork(): in a threaded
    // process the child may only make async-signal-safe calls until exec.
    std::vector<std::string> env;
    std::string userZdotdir;
    bool hadZdotdir = false, hasLocale = false;
    for (char **e = environ; *e; e++) {
        std::string kv = *e;
        std::string key = kv.substr(0, kv.find('='));
        if (key == "ZDOTDIR") {
            hadZdotdir = true;
            userZdotdir = kv.substr(kv.find('=') + 1);
            if (_integrated) continue;
        }
        if (key == "TERM" || key == "TERM_PROGRAM" ||
            key == "TERM_PROGRAM_VERSION" || key == "TERM_SESSION_ID" ||
            key == "COLORTERM" ||
            key == "COLUMNS" || key == "LINES" ||
            key == "MINICODE_USER_ZDOTDIR")
            continue;
        if (key == "LANG" || key == "LC_ALL" || key == "LC_CTYPE")
            hasLocale = true;
        env.push_back(kv);
    }
    // Colors, cursor movement and full-screen programs are all understood:
    // the log follows ordinary output and the grid takes over for programs
    // that draw a screen, so pagers are left to the user's own settings.
    env.push_back("TERM=xterm-256color");
    env.push_back("COLORTERM=truecolor");
    env.push_back("TERM_PROGRAM=MiniCode");
    if (!hasLocale) env.push_back("LANG=en_US.UTF-8");  // apps get no LANG
    if (_integrated) {
        env.push_back(std::string("ZDOTDIR=") + zdot.fileSystemRepresentation);
        if (hadZdotdir) env.push_back("MINICODE_USER_ZDOTDIR=" + userZdotdir);
    }
    std::vector<char *> envp;
    for (std::string &s : env) envp.push_back(&s[0]);
    envp.push_back(nullptr);

    char arg0[] = "-zsh", argI[] = "-i", argZ[] = "+Z";
    char *argv[] = {arg0, argI, argZ, nullptr};   // leading '-': login shell
    std::string cwd = _cwd.fileSystemRepresentation;
    long maxFd = sysconf(_SC_OPEN_MAX);
    if (maxFd < 0 || maxFd > 65536) maxFd = 65536;

    _stream = TerminalStream();
    _atPrompt = NO;
    _commandStarted = NO;
    _userCommand = NO;
    _stickyGrid = NO;
    _winsize = {};
    [self updateWindowSize];
    struct winsize ws = _winsize;
    _screen = TerminalScreen(ws.ws_col, ws.ws_row);

    int master = -1;
    pid_t pid = forkpty(&master, nullptr, nullptr, &ws);
    if (pid == 0) {
        // Child: restore default signal handling, drop inherited descriptors.
        int sigs[] = {SIGINT, SIGQUIT, SIGTSTP, SIGTTIN, SIGTTOU, SIGPIPE,
                      SIGCHLD, SIGHUP, SIGTERM, SIGALRM, SIGWINCH};
        for (int s : sigs) signal(s, SIG_DFL);
        sigset_t none;
        sigemptyset(&none);
        sigprocmask(SIG_SETMASK, &none, nullptr);
        for (long fd = 3; fd < maxFd; fd++) close((int)fd);
        if (chdir(cwd.c_str()) != 0) (void)chdir("/");
        execve("/bin/zsh", argv, envp.data());
        _exit(127);
    }
    if (pid < 0) {
        [self appendLine:[NSString stringWithFormat:@"Could not start shell: %s",
                          strerror(errno)] color:THex(0xF48771)];
        return;
    }

    struct termios t;
    if (tcgetattr(master, &t) == 0) {   // backspace over multi-byte characters
        t.c_iflag |= IUTF8;
        tcsetattr(master, TCSANOW, &t);
    }
    fcntl(master, F_SETFD, FD_CLOEXEC);

    _master = master;
    _shellPid = pid;
    _shellStarted = [NSDate date];
    int generation = ++_generation;

    __weak TerminalView *weakSelf = self;
    dispatch_source_t src = dispatch_source_create(
        DISPATCH_SOURCE_TYPE_READ, (uintptr_t)master, 0, _ioQueue);
    dispatch_source_set_event_handler(src, ^{
        char buf[16384];
        ssize_t n = read(master, buf, sizeof buf);
        if (n > 0) {
            NSData *data = [NSData dataWithBytes:buf length:(NSUInteger)n];
            dispatch_async(dispatch_get_main_queue(), ^{
                [weakSelf receive:data generation:generation];
            });
        } else if (n == 0 || (errno != EAGAIN && errno != EINTR)) {
            // EIO: every process holding the pty's other end has gone.
            dispatch_source_cancel(src);
        }
    });
    dispatch_source_set_cancel_handler(src, ^{
        close(master);
        dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY, 0), ^{
            int status = 0;
            waitpid(pid, &status, 0);
            dispatch_async(dispatch_get_main_queue(), ^{
                [weakSelf shellExited:generation];
            });
        });
    });
    _readSource = src;
    dispatch_resume(src);
}

- (void)shellExited:(int)generation {
    if (generation != _generation) return;   // replaced or torn down
    _readSource = nil;
    _master = -1;
    _shellPid = 0;
    _atPrompt = NO;
    _stickyGrid = NO;
    [self stopRawWatch];
    [self updateMode];           // back to the log (_master is -1 now)
    [self updateSecureInput];
    [self ensureNewline];
    // Restart right away, unless the shell is dying at startup; then wait for
    // Enter so a broken startup file can't spin in a loop.
    if (-[_shellStarted timeIntervalSinceNow] > 2.0) {
        [self appendLine:@"[shell exited — restarting]" color:THex(0x6A9955)];
        [self startShell];
    } else {
        [self appendLine:@"[shell exited — press Enter to start a new one]"
                   color:THex(0xF48771)];
    }
}

- (NSString *)quote:(NSString *)s {   // single-quote for the shell
    return [NSString stringWithFormat:@"'%@'",
            [s stringByReplacingOccurrencesOfString:@"'" withString:@"'\\''"]];
}

- (void)sendBytes:(const char *)bytes length:(size_t)length {
    while (_master >= 0 && length > 0) {
        ssize_t n = write(_master, bytes, length);
        if (n < 0) {
            if (errno == EINTR) continue;
            return;
        }
        bytes += n;
        length -= (size_t)n;
    }
}

- (void)sendText:(NSString *)text {
    const char *utf8 = text.UTF8String;
    if (utf8) [self sendBytes:utf8 length:strlen(utf8)];
}

- (void)sendControl:(char)byte {
    [self sendBytes:&byte length:1];
}

// ---------------------------------------------------------------- output
- (void)receive:(NSData *)data generation:(int)generation {
    if (generation != _generation) return;
    _screen.feed((const char *)data.bytes, data.length);
    std::string replies = _screen.takeReplies();   // e.g. cursor position
    if (!replies.empty()) [self sendBytes:replies.data() length:replies.size()];
    auto events = _stream.feed((const char *)data.bytes, data.length);
    NSTextStorage *ts = self.output.textStorage;
    [ts beginEditing];
    for (const TermEvent &e : events) {
        switch (e.kind) {
        case TermEvent::Line:
            [self replaceLiveLine:e.runs ended:e.ended];
            break;
        case TermEvent::PromptStart:
            _atPrompt = YES;
            _commandStarted = NO;
            _stickyGrid = NO;
            [self stopRawWatch];
            break;
        case TermEvent::CommandStart:
            _commandStarted = YES;
            [self startRawWatch];
            break;
        case TermEvent::CommandEnd:
            if (_userCommand) {
                _userCommand = NO;
                [self ensureNewline];
                if (e.status != 0)
                    [self appendLine:[NSString stringWithFormat:@"exit %d",
                                      e.status] color:THex(0xF48771)];
            }
            break;
        case TermEvent::Directory:
            _cwd = [[NSFileManager defaultManager]
                stringWithFileSystemRepresentation:e.text.c_str()
                                            length:e.text.size()];
            [self updatePrompt];
            break;
        }
    }
    [ts endEditing];
    [self updateMode];
    if (_gridMode) [self.grid screenChanged];
    else [self scrollToEnd];
    [self updateSecureInput];
}

// ---------------------------------------------------------------- styling
static NSFont *TermFont(BOOL bold, BOOL italic) {
    static NSFont *fonts[4];
    int i = (bold ? 1 : 0) | (italic ? 2 : 0);
    if (!fonts[i]) {
        NSFont *f = [NSFont monospacedSystemFontOfSize:12
            weight:bold ? NSFontWeightBold : NSFontWeightRegular];
        if (italic) {
            NSFontDescriptor *d = [f.fontDescriptor fontDescriptorWithSymbolicTraits:
                f.fontDescriptor.symbolicTraits | NSFontDescriptorTraitItalic];
            f = [NSFont fontWithDescriptor:d size:12] ?: f;
        }
        fonts[i] = f;
    }
    return fonts[i];
}

- (NSDictionary *)attributesForStyle:(const TermStyle &)st {
    const Settings &cfg = [AppSettings shared].settings;
    bool defaultFg = st.fg.kind == TermColor::Default;
    Rgba fg = defaultFg ? cfg.text(Surface::Terminal) : Rgba::hex(st.fg.rgb());
    bool hasBg = st.bg.kind != TermColor::Default;
    // Inverse text gets a solid background even on a see-through panel.
    Rgba bg = Rgba::hex(hasBg ? st.bg.rgb()
                              : cfg.background(Surface::Terminal).rgb());
    if (st.inverse) { std::swap(fg, bg); hasBg = true; defaultFg = false; }

    NSMutableDictionary *a = [NSMutableDictionary dictionary];
    a[NSFontAttributeName] = TermFont(st.bold, st.italic);
    NSColor *fgColor = MCColor(fg);
    if (st.dim) fgColor = [fgColor colorWithAlphaComponent:fg.a * 0.6];
    a[NSForegroundColorAttributeName] = fgColor;
    if (defaultFg) a[kDefaultFgAttribute] = @(st.dim);
    if (hasBg) a[NSBackgroundColorAttributeName] = MCColor(bg);
    if (st.underline) a[NSUnderlineStyleAttributeName] = @(NSUnderlineStyleSingle);
    if (st.strike) a[NSStrikethroughStyleAttributeName] = @(NSUnderlineStyleSingle);
    return a;
}

// ---------------------------------------------------------------- output
// Replace the live line (everything from _liveStart on) with `runs`. If the
// line ended, add its newline and start the next live line after it.
- (void)replaceLiveLine:(const std::vector<TermRun> &)runs ended:(bool)ended {
    NSMutableAttributedString *line = [[NSMutableAttributedString alloc] init];
    for (const TermRun &r : runs) {
        NSString *s = [[NSString alloc] initWithBytes:r.text.data()
                                               length:r.text.size()
                                             encoding:NSUTF8StringEncoding];
        if (!s.length) continue;
        [line appendAttributedString:[[NSAttributedString alloc]
            initWithString:s attributes:[self attributesForStyle:r.style]]];
    }
    if (ended)
        [line appendAttributedString:[[NSAttributedString alloc]
            initWithString:@"\n" attributes:[self attributesForStyle:TermStyle()]]];

    NSTextStorage *ts = self.output.textStorage;
    if (_liveStart > ts.length) _liveStart = ts.length;
    [ts replaceCharactersInRange:NSMakeRange(_liveStart, ts.length - _liveStart)
            withAttributedString:line];
    if (ended) _liveStart = ts.length;
}

// Panel text (headers, statuses) goes below a live line that has content, so
// end that line first and tell the stream it now starts afresh.
- (void)ensureNewline {
    NSTextStorage *ts = self.output.textStorage;
    if (_liveStart < ts.length) {
        [ts appendAttributedString:[[NSAttributedString alloc]
            initWithString:@"\n" attributes:[self attributesForStyle:TermStyle()]]];
        _stream.breakLine();
    }
    _liveStart = ts.length;
}

- (void)appendLine:(NSString *)line color:(NSColor *)color {
    [self ensureNewline];
    NSDictionary *attrs = @{
        NSFontAttributeName: TermFont(NO, NO),
        NSForegroundColorAttributeName: color,
    };
    NSTextStorage *ts = self.output.textStorage;
    [ts appendAttributedString:[[NSAttributedString alloc]
        initWithString:[line stringByAppendingString:@"\n"] attributes:attrs]];
    _liveStart = ts.length;
    [self scrollToEnd];
}

- (void)scrollToEnd {
    [self.output scrollRangeToVisible:
        NSMakeRange(self.output.textStorage.length, 0)];
}

@end
